var character = [
    {letter: 'À', int: '&Agrave;'},
    {letter: 'Á', int: '&Aacute;'},
    {letter: 'Â', int: '&Acirc;'},
    {letter: 'Ã', int: '&Atilde;'},
    {letter: 'Ä', int: '&Auml;'},
    {letter: 'Å', int: '&Aring;'},
    {letter: 'Æ', int: '&AElig;'},
    {letter: 'Ç', int: '&Ccedil;'},
    {letter: 'È', int: '&Egrave;'},
    {letter: 'É', int: '&Eacute;'},
    {letter: 'Ê', int: '&Ecirc;'},
    {letter: 'Ë', int: '&Euml;'},
    {letter: 'Ì', int: '&Igrave;'},
    {letter: 'Í', int: '&Iacute;'},
    {letter: 'Î', int: '&Icirc;'},
    {letter: 'Ï', int: '&Iuml;'},
    {letter: 'Ð', int: '&ETH;'},
    {letter: 'Ñ', int: '&Ntilde;'},
    {letter: 'Ò', int: '&Ograve;'},
    {letter: 'Ó', int: '&Oacute;'},
    {letter: 'Ô', int: '&Ocirc;'},
    {letter: 'Õ', int: '&Otilde;'},
    {letter: 'Ö', int: '&Ouml;'},
    {letter: 'Ø', int: '&Oslash;'},
    {letter: 'Ù', int: '&Ugrave;'},
    {letter: 'Ú', int: '&Uacute;'},
    {letter: 'Û', int: '&Ucirc;'},
    {letter: 'Ü', int: '&Uuml;'},
    {letter: 'Ý', int: '&Yacute;'},

]
export {character}
